### ISSUE TITLE
Issue in running the first example

### ISSUE THREAD

**Issue by DeltaMethod721** [yycunc/SAFEclustering#2]
`path <- "/Users/maod/DM_revision"`
`cluster.ensemble <- SAFE(cluster_results = cluster.results, 
                          program.dir = path, 
                          MCLA = TRUE, CSPA = TRUE, HGPA = TRUE, SEED = 123)`
[1] "Cluster ensembles using HGPA"
[1] "wgraph: writing graph222"
[1] "wgraph: 500 vertices and 14 non-zero hyperedges"
[1] "cluster ensembles: /Users/maod/DM_revision/shmetis graph222 2 5"
sh: /Users/maod/DM_revision/shmetis: Permission denied
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'graph222.part.2': No such file or directory

Here's my info,
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

**Comment by mzhq** [comment]
Met the same issue. And I already put both gpmetis and shmetis in my working dir.
Besides, my platform is linux.
Have you solved this problem?

**Comment by mzhq** [comment]
I use CMD "chmod +x gpmetis shmetis" and now it works.

**Comment by adiko-junior** [comment]
Hello everyone excuse me,
the gpmetis shmetis programs is it possible to use with Windows.

**Comment by yycunc** [comment]
> `path <- "/Users/maod/DM_revision"` `cluster.ensemble <- SAFE(cluster_results = cluster.results, program.dir = path, MCLA = TRUE, CSPA = TRUE, HGPA = TRUE, SEED = 123)` [1] "Cluster ensembles using HGPA" [1] "wgraph: writing graph222" [1] "wgraph: 500 vertices and 14 non-zero hyperedges" [1] "cluster ensembles: /Users/maod/DM_revision/shmetis graph222 2 5" sh: /Users/maod/DM_revision/shmetis: Permission denied Error in file(file, "rt") : cannot open the connection In addition: Warning message: In file(file, "rt") : cannot open file 'graph222.part.2': No such file or directory
> 
> Here's my info, R version 3.5.2 (2018-12-20) Platform: x86_64-apple-darwin15.6.0 (64-bit) Running under: macOS Sierra 10.12.6
> 
> Matrix products: default BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib
> 
> locale: [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

Hi, both gpmetis and shmetis should be executable before using. Please try to use chmod to change their permission status.

And if gpmetis or shmetis was executed but unfortunately failed, there should be graph files in your working directory. So you have to delete them before the next run.

**Comment by yycunc** [comment]
> Hello everyone excuse me, the gpmetis shmetis programs is it possible to use with Windows.

Unfortunately not. They can be only executed on Mac OS or Linux systems.

**Comment by adiko-junior** [comment]
Thank you very much.
Best.
