### ISSUE TITLE
Seurat clustering does not work as intended

### ISSUE THREAD

**Issue by jr-leary7** [yycunc/SAFEclustering#4]
The `seurat_SAFE()` function uses the `low.genes` variable when calling `CreateSeuratObject()`, but `low.genes` is not passed from `individual_clustering()` (where it is defined) to `seurat_SAFE()` and thus is not in scope when it is called. Adding `low.genes` as an argument to `seurat_SAFE()` should fix this.

**Comment by yycunc** [comment]
Sorry for missing your great comment. Thanks for pointing this out and we have already fixed this issue.
